- id: copy-root-outputs
  name: copy root outputs
  description: Update all modules with outputs.tf from root module.
  entry: copy-root-outputs
  language: python
  pass_filenames: false
  files: ^.*\.tf$

- id: update-readme-toc-modules
  name: update readme toc modules
  description: Update README.md with TOC of for all modules and stacks in repository.
  entry: update-readme-toc-modules
  language: python
  pass_filenames: false
  files: ^(README.md|.*\.tf)$

- id: update-tf-docs
  name: update tf-docs generation
  description: Update Pre-Commit config to generate TF Docs for all modules in repository.
  entry: update-tf-docs
  language: python
  pass_filenames: false
  files: ^(.pre-commit-config.yaml|.*\.tf)$
