name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Pre-Commit Run
        uses: pre-commit/action@v3.0.0
